//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FENIX_NOMINAEntities : DbContext
    {
        public FENIX_NOMINAEntities()
            : base("name=FENIX_NOMINAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTOes { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOes { get; set; }
        public virtual DbSet<PUESTO> PUESTOes { get; set; }
        public virtual DbSet<RG_TRANSACCIONES> RG_TRANSACCIONES { get; set; }
        public virtual DbSet<SOLICITUD> SOLICITUDs { get; set; }
        public virtual DbSet<TIPO_INGRESO> TIPO_INGRESO { get; set; }
        public virtual DbSet<TIPO_NOMINA> TIPO_NOMINA { get; set; }
        public virtual DbSet<TP_DEDUCCIONES> TP_DEDUCCIONES { get; set; }
        public virtual DbSet<TRANSACCION> TRANSACCIONs { get; set; }
    }
}
