//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FENIX_NOMINAEntities : DbContext
    {
        public FENIX_NOMINAEntities()
            : base("name=FENIX_NOMINAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<LOGIN1> LOGIN1 { get; set; }
        public virtual DbSet<PUESTO> PUESTO { get; set; }
        public virtual DbSet<RG_TRANSACCIONES> RG_TRANSACCIONES { get; set; }
        public virtual DbSet<SOLICITUD> SOLICITUD { get; set; }
        public virtual DbSet<TIPO_INGRESO> TIPO_INGRESO { get; set; }
        public virtual DbSet<TIPO_NOMINA> TIPO_NOMINA { get; set; }
        public virtual DbSet<TP_DEDUCCIONES> TP_DEDUCCIONES { get; set; }
        public virtual DbSet<TRANSACCION> TRANSACCION { get; set; }
    
        public virtual int RegistroUser(string nombre, string correo, string passw, ObjectParameter registrado, ObjectParameter mensaje)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var passwParameter = passw != null ?
                new ObjectParameter("Passw", passw) :
                new ObjectParameter("Passw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistroUser", nombreParameter, correoParameter, passwParameter, registrado, mensaje);
        }
    
        public virtual ObjectResult<Nullable<int>> ValidarUser(string correo, string pass)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ValidarUser", correoParameter, passParameter);
        }
    }
}
