//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.DEPARTAMENTOes = new HashSet<DEPARTAMENTO>();
            this.RG_TRANSACCIONES = new HashSet<RG_TRANSACCIONES>();
        }
    
        public int ID_EMPLE { get; set; }
        public string CEDULA { get; set; }
        public string NOMBRE { get; set; }
        public int SALARIO { get; set; }
        public int ID_DEPARTAMENTO { get; set; }
        public int ID_PUESTO { get; set; }
        public int ID_NOMINA { get; set; }
    
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPARTAMENTO> DEPARTAMENTOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RG_TRANSACCIONES> RG_TRANSACCIONES { get; set; }
        public virtual PUESTO PUESTO { get; set; }
        public virtual TIPO_NOMINA TIPO_NOMINA { get; set; }
    }
}
