//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.DEPARTAMENTO1 = new HashSet<DEPARTAMENTO>();
            this.RG_TRANSACCIONES = new HashSet<RG_TRANSACCIONES>();
        }
    
        public int ID_EMPLE { get; set; }
        public string CEDULA { get; set; }
        public string NOMBRE { get; set; }
        public int SALARIO { get; set; }
        public int ID_DEPARTAMENTO { get; set; }
        public int ID_PUESTO { get; set; }
        public int ID_NOMINA { get; set; }
    
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPARTAMENTO> DEPARTAMENTO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RG_TRANSACCIONES> RG_TRANSACCIONES { get; set; }
        public virtual PUESTO PUESTO { get; set; }
        public virtual TIPO_NOMINA TIPO_NOMINA { get; set; }
    }
}
