//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN1
    {
        public int ID_USER { get; set; }
        public string NOMBRES { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASEÑA { get; set; }
        public string TIPO_USUARIO { get; set; }
    }
}
