//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RG_TRANSACCIONES
    {
        public int ID_RGTRANS { get; set; }
        public int ID_EMPLEADO { get; set; }
        public int ID_INGRESO { get; set; }
        public int ID_DEDUCCION { get; set; }
        public int ID_TIPO_TRANSACCION { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal MONTO { get; set; }
        public string ESTADO { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual TP_DEDUCCIONES TP_DEDUCCIONES { get; set; }
        public virtual TIPO_INGRESO TIPO_INGRESO { get; set; }
        public virtual TRANSACCION TRANSACCION { get; set; }
    }
}
