//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        public int ID_NOTI { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string TITULO { get; set; }
        public string MENSAJE { get; set; }
    }
}
