//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        public int ID_NOTI { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string TITULO { get; set; }
        public string MENSAJE { get; set; }
    }
}
